### ISSUE TITLE
mutate over cnae_2dig breaks load_pnadc

### ISSUE THREAD

**Issue by lauratregadas** [datazoompuc/datazoom.social#55]
Lines 446-544 of the load_pnadc function mutates cnae_2dig three times. 

I tried running load_pnadc: load_pnadc(year = 2017, panel = "advanced")
I got the following error: 
Error in `purrr::map2()`:
ℹ In index: 1.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `cnae_2dig = dplyr::case_match(...)`.
Caused by error in `dplyr::case_match()`:
! Can't convert `..1 (left)` <character> to <double>.
Run `rlang::last_trace()` to see where the error occurred.
>   load_pnadc(year = c(2013:2014), panel = "advanced")
Error in `purrr::map2()`:
! Can't recycle `.x` (size 2) to match `.y` (size 8).
Run `rlang::last_trace()` to see where the error occurred.

I believe the problem is in these lines of code, as 1402:1409 is size 8:
#
```r
cnae_2dig = dplyr::case_match(
        V4013,
        c(paste0(0, 1201:1209), paste0(0, 1402:1409), "01999") ~ "Pecu\u00e1ria e cria\u00e7\u00e3o de animais",
        .default = cnae_2dig
```

**Comment by lauratregadas** [comment]
I realised I was running the function with "year" instead of "years" as parameter. Still, I put as.numeric(V4013) in the code. Nonetheless, I still get the same error when running load_pnadc(years = c(2013:2014), panel = "advanced")

**Comment by lauratregadas** [comment]
Furthermore, I get unloaded package errors. Such as:
Error in `purrr::map2()`:
ℹ In index: 1.
Caused by error in `df %>% mutate(across(everything(), as.numeric))`:
! could not find function "%>%"
Run `rlang::last_trace()` to see where the error occurred.

However, load_pnadc's line 15 reads:
```r
#' @importFrom magrittr %>%
```

**Comment by IgorRigolon** [comment]
@lauratregadas V4013 was always numeric. What I meant was that the code is currently

```
      cnae_2dig = dplyr::case_match(
        V4013,
        c(paste0(0, 1201:1209), paste0(0, 1402:1409), "01999") ~ "Pecu\u00e1ria e cria\u00e7\u00e3o de animais",
        .default = cnae_2dig
      )
```

when it should be

```
      cnae_2dig = dplyr::case_match(
        V4013,
        as.numeric(c(paste0(0, 1201:1209), paste0(0, 1402:1409), "01999")) ~ "Pecu\u00e1ria e cria\u00e7\u00e3o de animais",
        .default = cnae_2dig
      )
```

so that the contents of `case_match` match the variable type.
